name: resto_lite
description: "App for Restaurant Management"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Use as default SVG image loader, prefer use SVG as image asset
  flutter_svg: ^2.0.9

  # Routing Library
  go_router: ^14.3.0

  #Flutter plugin for discovering the state of the network
  connectivity_plus: ^6.1.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

  # Use as Network Client
  dio: ^5.7.0
  dio_http_formatter: ^3.2.1

  # dio client generator
  retrofit: ^4.4.1

  # Functional programming
  dartz: ^0.10.1

  # Use for State Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  riverpod: ^2.6.1

  # Flutter library to load and cache network images.
  cached_network_image: ^3.4.1

  # store data in secure storage
  flutter_secure_storage: ^9.2.2 

  # Use hive to save local data
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # logger
  logger: ^2.5.0

  # Firebase
  firebase_core: ^3.9.0
  firebase_analytics: ^11.3.6
  firebase_crashlytics: ^4.2.0

  # Code generator for data classes, unions and cloning.
  freezed_annotation: ^2.4.4
  # Use as default JSON parser
  json_annotation: ^4.9.0
  equatable: ^2.0.7

  # Customize splash screen
  flutter_native_splash: ^2.4.3

  # Use for localization
  intl: ^0.19.0

  # Use for custom toast with Status, ex : Loading,Success,Failed
  oktoast: ^3.4.0

  # Use for responsive UI, set default size base on Mock Up
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^9.0.0
  retrofit_generator: ^8.1.0

  flutter_launcher_icons: ^0.14.1

  lint: ^2.3.0
  build_runner: ^2.4.13
  custom_lint: ^0.7.0
  flutter_lints: ^5.0.0

  http_mock_adapter: ^0.6.1

  riverpod_generator: ^2.6.3
  riverpod_lint: ^2.6.3

  freezed: ^2.5.7
  json_serializable: ^6.7.1

dependency_overrides:
  meta: ^1.16.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
